export enum ROUTES {
  HOME = "/",
  SERVICES = "/services",
  PARTNERS = "/partners",
  TESTIMONIALS = "/testimonials",
  LOGIN = "/login",
  LOGOUT = "/logout",
  OTP = "/otp",
  SET_PHONE = "/set-phone",
  REGISTER = "/register",
  SIGNUP = "/signup",

  SERVICE_PROVIDER_REGISTRATION_FORM = "/service-provider/register",

  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  SETTINGS = "/settings",
  ABOUT = "/about",
  CONTACT = "/contact",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_OF_SERVICE = "/terms-of-service",
  HELP = "/help",
  FAQ = "/faq",
  BLOG = "/blog",
  NOT_FOUND = "/404",
}
