import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { PlaygroundHeader } from "@/components/playgrounds/playground-header";
import { AppHeader } from "@/components/organisms/app-header";
import { AppFooter } from "@/components/organisms/app-footer";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/lib/api/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "هن لهن",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="ar" dir="rtl" suppressHydrationWarning>
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col flex-1`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <AppHeader />

              {/* <PlaygroundHeader /> */}
              <main className="flex-grow">{children}</main>
              <AppFooter />
              <Toaster />
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
