// lib/validation/service-provider-step1-config.ts
import { FormConfig } from "./types";
import { serviceProviderValidations } from "./validators";

export const serviceProviderStep1Config: FormConfig = {
  title: "معلومات الخدمة الأساسية",
  description: "يرجى ملء المعلومات الأساسية عن خدمتك",
  submitButtonText: "التالي: تحميل الوثائق",
  fields: [
    {
      name: "logo_image_file",
      label: "شعار الخدمة",
      placeholder: "اختر صورة الشعار",
      type: "file",
      required: true,
      validationRules: serviceProviderValidations.logo_image_file,
      accept: "image/*",
      helpText: "يرجى اختيار صورة واضحة لشعار خدمتك (PNG, JPG)",
      gridCols: 6,
    },
    {
      name: "service_name",
      label: "اسم الخدمة",
      placeholder: "مثال: خدمات التصميم الجرافيكي",
      type: "text",
      required: true,
      validationRules: serviceProviderValidations.service_name,
      gridCols: 6,
    },
    {
      name: "service_description",
      label: "وصف الخدمة",
      placeholder: "اكتب وصفاً مفصلاً عن خدماتك...",
      type: "textarea",
      required: true,
      validationRules: serviceProviderValidations.service_description,
      rows: 4,
      gridCols: 12,
    },
    {
      name: "service_category_id",
      label: "فئة الخدمة",
      placeholder: "اختر فئة الخدمة",
      type: "select",
      required: true,
      validationRules: serviceProviderValidations.service_category_id,
      options: [], // Will be populated dynamically
      gridCols: 6,
    },
    {
      name: "governorate_id",
      label: "المحافظة",
      placeholder: "اختر المحافظة",
      type: "select",
      required: true,
      validationRules: serviceProviderValidations.governorate_id,
      options: [], // Will be populated dynamically
      gridCols: 6,
    },
    {
      name: "years_of_experience",
      label: "سنوات الخبرة",
      placeholder: "مثال: 5",
      type: "number",
      required: true,
      validationRules: serviceProviderValidations.years_of_experience,
      min: 0,
      max: 50,
      gridCols: 6,
    },
    {
      name: "service_delivery_method",
      label: "طريقة تقديم الخدمة",
      placeholder: "اختر طريقة التقديم",
      type: "select",
      required: true,
      validationRules: serviceProviderValidations.service_delivery_method,
      options: [
        { value: "online", label: "عبر الإنترنت" },
        { value: "offline", label: "في المكان" },
        { value: "both", label: "كلاهما" },
      ],
      gridCols: 6,
    },
    {
      name: "address",
      label: "العنوان",
      placeholder: "العنوان التفصيلي (مطلوب للخدمات في المكان)",
      type: "textarea",
      required: false,
      validationRules: serviceProviderValidations.address,
      rows: 2,
      gridCols: 12,
      conditionalDisplay: {
        field: "service_delivery_method",
        values: ["offline", "both"],
      },
    },
    {
      name: "official_url",
      label: "الموقع الرسمي",
      placeholder: "https://example.com (اختياري)",
      type: "url",
      required: false,
      validationRules: serviceProviderValidations.official_url,
      gridCols: 6,
      conditionalDisplay: {
        field: "service_delivery_method",
        values: ["online", "both"],
      },
    },
    {
      name: "bio",
      label: "السيرة الذاتية",
      placeholder: "اكتب سيرتك الذاتية ومؤهلاتك...",
      type: "textarea",
      required: true,
      validationRules: serviceProviderValidations.bio,
      rows: 4,
      gridCols: 12,
    },
    {
      name: "services",
      label: "الخدمات الفرعية",
      placeholder:
        "مثال: تصميم شعارات، تصميم بوسترات، تصميم هوية بصرية (اختياري)",
      type: "text",
      required: false,
      validationRules: serviceProviderValidations.services,
      helpText: "اكتب الخدمات مفصولة بفاصلة",
      gridCols: 12,
    },
    {
      name: "facebook_url",
      label: "رابط فيسبوك",
      placeholder: "https://facebook.com/yourpage (اختياري)",
      type: "url",
      required: false,
      validationRules: serviceProviderValidations.facebook_url,
      gridCols: 6,
    },
    {
      name: "instagram_url",
      label: "رابط إنستقرام",
      placeholder: "https://instagram.com/yourpage (اختياري)",
      type: "url",
      required: false,
      validationRules: serviceProviderValidations.instagram_url,
      gridCols: 6,
    },
    {
      name: "whatsapp_url",
      label: "رابط واتساب",
      placeholder: "https://wa.me/201234567890 (اختياري)",
      type: "url",
      required: false,
      validationRules: serviceProviderValidations.whatsapp_url,
      gridCols: 6,
    },
    {
      name: "other_urls",
      label: "روابط أخرى",
      placeholder: "روابط إضافية مفصولة بفاصلة (حد أقصى 4)",
      type: "text",
      required: false,
      validationRules: serviceProviderValidations.other_urls,
      helpText:
        "مثال: https://linkedin.com/in/profile, https://behance.net/profile",
      gridCols: 6,
    },
    {
      name: "slug",
      label: "رابط الصفحة الشخصية",
      placeholder: "مثال: ahmed-designer",
      type: "text",
      required: true,
      validationRules: serviceProviderValidations.slug,
      helpText: "سيكون رابطك: honna-lahonna.com/providers/[slug]",
      gridCols: 6,
    },
    {
      name: "keywords",
      label: "الكلمات المفتاحية",
      placeholder: "كلمات مفتاحية للبحث مفصولة بفاصلة",
      type: "text",
      required: false,
      validationRules: serviceProviderValidations.keywords,
      helpText: "مثال: تصميم, جرافيك, شعارات, هوية بصرية",
      gridCols: 6,
    },
  ],
};
